steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - >
        git config --global url."https://$$GITHUB_TOKEN@github.com/loveholidays/".insteadOf "https://github.com/loveholidays/"
    secretEnv:
      - GITHUB_TOKEN
  - name: golang:1.22
    entrypoint: /bin/bash
    dir: git-slack-bot
    env: [ 'GOPRIVATE=github.com/loveholidays/*' ]
    args:
      - -c
      - |
        go mod vendor

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: docker-build
    args:
      - --destination=eu.gcr.io/$PROJECT_ID/git-slack-bot:$TAG_NAME
      - --context=dir://git-slack-bot
      - --cache=true
      - --cache-ttl=96h

timeout: 5400s
options:
  substitutionOption: ALLOW_LOOSE
  machineType: "N1_HIGHCPU_32"
secrets:
  - kmsKeyName: projects/loveholidays-ci-cd/locations/global/keyRings/cloud-build-keyring/cryptoKeys/cloud-build-key
    secretEnv:
      GITHUB_TOKEN: CiQAcY6cdyoBlnEJpbRvkEEKHXS9qoRR2oh1CD11tVxa1RwETFYSUQBOkaOA+jsSB9gPwV+EpWrmmnjP3b0vHwy8bI6c5XN3yb/EYRl8FSL3rAGHTSbvGANAWbl4tdSyyv+VLDcF+7lPcMn3KA1FqxycWZbmNOEh+g==
logsBucket: lh-cloud-build-logs
tags: ["git-slack-bot"]
