github:
  token: "$GITHUB_TOKEN"
  org: loveholidays
  team: Supply
  secretKey: "$GITHUB_WEBHOOK_SECRET"
  ignoredPRUsers:
    - dmitri-lerko
    - georgemalamidis-lh
    - BenAxelsen
  ignoredCommentUsers:
    - github-actions[bot]
  ignoredRepos:
    - flux

slack:
  token: "$SLACK_TOKEN"
  channelID: "C056ZCEG3JR"
  fetchMessageCount: 100
  emoji:
    approve: "+1"
    merge: "merged"
    close: "x"