github:
  token: "$GITHUB_TOKEN"
  org: organisation
  team: team
  secretKey: "$GITHUB_WEBHOOK_SECRET"
  ignoredPRUsers:
  ignoredCommentUsers:
  ignoredRepos:

slack:
  token: "$SLACK_TOKEN"
  channelID: "$CHANNEL_ID"
  fetchMessageCount: 100
  emoji:
    approve: "+1"
    merge: "merged"
    close: "x"