name: Bug Report
description: Report a bug to help us improve git-slack-bot
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of git-slack-bot are you running?
      placeholder: e.g., v1.0.0, latest, commit hash
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure bot with...
        2. Send webhook with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your git-slack-bot configuration (please remove sensitive data like tokens)
      render: yaml
      placeholder: |
        github:
          org: "your-org"
          team: "your-team"
        slack:
          channelID: "C1234567890"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (remove sensitive data)
      render: shell
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Deployment environment (Docker, Kubernetes, binary, etc.)
      placeholder: e.g., Docker on AWS, Kubernetes, local binary
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true