name: docker

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.repository == 'loveholidays/git-slack-bot' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ++ Export global vars for current job
        id: current-job
        run: |
          if [ ${{github.ref_name}} = "main" ]; then
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ghcr.io/loveholidays/git-slack-bot:${{ steps.current-job.outputs.VERSION }}